package com.myspace.wiedzmin;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GeraltKeySearch implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("fightDone")
	private boolean fightDone;

	public GeraltKeySearch() {
	}

	public boolean isFightDone() {
		return this.fightDone;
	}

	public void setFightDone(boolean fightDone) {
		this.fightDone = fightDone;
	}

	public GeraltKeySearch(boolean fightDone) {
		this.fightDone = fightDone;
	}

}