package com.myspace.wiedzmin;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KeySearchErrorDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String error;

	public KeySearchErrorDO() {
	}

	public java.lang.String getError() {
		return this.error;
	}

	public void setError(java.lang.String error) {
		this.error = error;
	}

	public KeySearchErrorDO(java.lang.String error) {
		this.error = error;
	}

}