package com.myspace.wiedzmin;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RadioObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String text;

	private java.lang.String value;

	public RadioObject() {
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public RadioObject(java.lang.String text, java.lang.String value) {
		this.text = text;
		this.value = value;
	}

}