package com.myspace.wiedzmin;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RadioObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RadioObject() {
    }




}