package com.myspace.wiedzmin;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RadioObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String text;

	public RadioObject() {
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public RadioObject(java.lang.String text) {
		this.text = text;
	}

}